# Generated by Django 4.2.5 on 2023-11-03 15:05

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='CiuNom', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='SteNom', max_length=100, unique=True)),
                ('ciudad', models.ForeignKey(db_column='SitCiuID', default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='EquNom', max_length=50, unique=True, validators=[core.models.Validadores.valida_sin_espacios])),
                ('descripcion', models.CharField(db_column='EquDsc', max_length=100)),
                ('site', models.ForeignKey(blank=True, db_column='EquSitID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.site')),
            ],
        ),
    ]
