# Generated by Django 4.2.5 on 2023-11-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='en_monitoreo',
            field=models.BooleanField(db_column='EquMon', default=False, verbose_name='En monitoreo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='padres',
            field=models.ManyToManyField(blank=True, related_name='Equ_parents', to='core.equipo', verbose_name='Padres'),
        ),
    ]
