# Generated by Django 4.2.5 on 2023-11-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_equipo_en_monitoreo_equipo_padres'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='ip',
            field=models.GenericIPAddressField(blank=True, db_column='EquIP', null=True, protocol='IPv4', unique=True, verbose_name='IP'),
        ),
    ]
