# Generated by Django 4.2.5 on 2023-12-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_equipo_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='comunidad_snmp',
            field=models.CharField(blank=True, db_column='EquComSNMP', max_length=40, null=True, verbose_name='Comunidad SNMP'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='monitorear_trafico',
            field=models.BooleanField(db_column='EquMonTra', default=False, verbose_name='Monitoreando trafico'),
        ),
    ]
