# Generated by Django 4.2.5 on 2023-09-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(db_column='NagHstIP', protocol='IPv4', unique=True, verbose_name='IP')),
                ('hostname', models.CharField(db_column='NagHstNme', max_length=50, unique=True, verbose_name='Hostname')),
                ('template', models.CharField(db_column='NagHstTem', max_length=50, verbose_name='Plantilla a utilizar')),
            ],
        ),
    ]
