# Generated by Django 4.2.5 on 2023-09-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='alias',
            field=models.CharField(db_column='NagHstDsc', default=1, max_length=100, verbose_name='Hostname'),
            preserve_default=False,
        ),
    ]
