# Generated by Django 4.2.5 on 2023-09-17 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nagios', '0002_host_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nagios.host', verbose_name='Padre'),
        ),
    ]
