# Generated by Django 4.2.5 on 2023-09-17 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nagios', '0003_host_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='parent',
        ),
        migrations.AddField(
            model_name='host',
            name='parents',
            field=models.ForeignKey(blank=True, db_column='NagHstPar', null=True, on_delete=django.db.models.deletion.CASCADE, to='nagios.host', verbose_name='Padre'),
        ),
    ]
