# Generated by Django 4.2.5 on 2023-09-18 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nagios', '0005_alter_host_parents'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='NagHstGrpNom', max_length=50, unique=True, verbose_name='Nombre')),
                ('alias', models.CharField(db_column='NagHstGrpDsc', max_length=100, verbose_name='Descripcion del grupo')),
            ],
        ),
        migrations.AlterField(
            model_name='host',
            name='alias',
            field=models.CharField(db_column='NagHstDsc', max_length=100, verbose_name='Descripcion del host'),
        ),
        migrations.AddField(
            model_name='host',
            name='hostgroup',
            field=models.ForeignKey(blank=True, db_column='NagHstGrpID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nagios.hostgroup', verbose_name='Hostgroup'),
        ),
    ]
