# Generated by Django 4.2.5 on 2023-09-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagios', '0006_hostgroup_alter_host_alias_host_hostgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='hostgroup',
        ),
        migrations.AddField(
            model_name='host',
            name='hostgroups',
            field=models.ManyToManyField(blank=True, null=True, related_name='host_groups', to='nagios.hostgroup', verbose_name='Hostgroups'),
        ),
    ]
