# Generated by Django 4.2.5 on 2023-09-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagios', '0007_remove_host_hostgroup_host_hostgroups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='hostgroups',
            field=models.ManyToManyField(blank=True, related_name='host_groups', to='nagios.hostgroup', verbose_name='Hostgroups'),
        ),
        migrations.RemoveField(
            model_name='host',
            name='parents',
        ),
        migrations.AddField(
            model_name='host',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='host_parents', to='nagios.host', verbose_name='Parents'),
        ),
    ]
