# Generated by Django 4.2.5 on 2023-11-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagios', '0008_alter_host_hostgroups_remove_host_parents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='template',
            field=models.CharField(db_column='NagHstTem', default='linux-server', max_length=50, verbose_name='Plantilla a utilizar'),
        ),
    ]
